services:
  nginx:
    image: nginx
    domainname: "myapp"
    build: .
    volumes:
     - ./public_html:/usr/share/nginx/html/
    ports:
     - "80:80"
    environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80